'use client';
import {useState} from 'react';
import CompanyLogo from './company-logo';
import {Sparkles,ArrowUpRight,Clock3,ShieldCheck,ChevronDown} from 'lucide-react';
import researchData from '../../lib/research-snapshots.json';
import type {IPO} from '../../lib/ipos';
export type ResearchSnapshot={id:string;name:string;date:string;source:string;verdict:string;summary:string;strengths:string[];risks:string[];nextStep:string;metrics:{label:string;value:string}[];coverage:string};
const records=researchData as ResearchSnapshot[];
export default function Research({ipos,onSelect,companyId}:{ipos:IPO[];onSelect:(p:IPO)=>void;companyId?:string}){
 const [filter,setFilter]=useState('All assessments');
 const candidates=companyId?records.filter(r=>r.id===companyId):records.filter(r=>ipos.some(p=>p.id===r.id));
 const filtered=candidates.filter(r=>filter==='All assessments'||r.verdict===filter);
 return <section className={'research-section '+(companyId?'in-detail':'')}><div className="research-banner"><div className="research-symbol"><Sparkles size={25}/></div><div><span className="eyebrow">AI RESEARCH · HUMAN JUDGMENT</span><h2>A clearer view of the numbers.</h2><p>AI-written assessments of growth, profitability, valuation and disclosed risks. Read the evidence before making a decision.</p></div><span className="snapshot-label"><Clock3 size={13}/> Dated snapshots</span></div><div className="research-disclosure"><ShieldCheck size={16}/><p>These are saved AI research opinions, not live predictions or personalized buy/sell advice. Market conditions and company disclosures may have changed since the date shown.</p></div>{!companyId&&<div className="research-controls"><strong>{candidates.length} company assessments</strong><label><select aria-label="Filter AI assessments" value={filter} onChange={e=>setFilter(e.target.value)}><option>All assessments</option><option>Worth researching</option><option>Valuation caution</option><option>Wait for disclosures</option></select><ChevronDown size={14}/></label></div>}
 <div className="research-list">{filtered.map(r=><article className="research-card" key={r.id}><div className="research-card-heading"><CompanyLogo id={r.id} name={r.name} source={r.source}/><div><span className={'research-verdict '+(r.verdict==='Worth researching'?'positive':r.verdict==='Valuation caution'?'caution':'neutral')}>{r.verdict}</span><h3>{r.name}</h3></div><span className="research-date">Reviewed {r.date}</span></div><p className="research-summary">{r.summary}</p><div className="research-metrics">{r.metrics.map(m=><div key={m.label}><span>{m.label}</span><strong>{m.value}</strong></div>)}</div><div className="research-reasons"><div><h4>What supports the case</h4><ul>{r.strengths.map(s=><li key={s}>{s}</li>)}</ul></div><div><h4>What needs caution</h4><ul>{r.risks.map(s=><li key={s}>{s}</li>)}</ul></div></div><div className="research-next"><Sparkles size={16}/><div><strong>Research recommendation</strong><p>{r.nextStep}</p></div></div><div className="research-card-foot"><span>Evidence: {r.coverage}</span><a href={r.source} target="_blank" rel="noreferrer">Review source <ArrowUpRight size={14}/></a>{!companyId&&ipos.some(p=>p.id===r.id)&&<button onClick={()=>onSelect(ipos.find(p=>p.id===r.id)!)}>Company details <ArrowUpRight size={14}/></button>}</div></article>)}</div>
 {!filtered.length&&<div className="notice">{companyId?'No dated AI assessment is available for this company yet. Review its financials and prospectus before considering an application.':'No assessments match this filter.'}</div>}<p className="fine-print">Method: source-reported financials and issue terms, interpreted by AI. Growth rates compare the two latest fiscal years where available. No GMP-based return forecasts, guaranteed outcomes or fabricated confidence scores.</p></section>
}
